CREATE TABLE users(
  userid INTEGER PRIMARY KEY,
  fullname VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  location VARCHAR(255),
  configs INTEGER []
);

CREATE TABLE configs(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  config JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
